#!/bin/bash

# نمایش IPv4
echo "Your IPv4 address is:"
ip -4 addr show | grep inet | awk '{print $2}' | cut -d/ -f1

# نمایش IPv6
echo "Your IPv6 address is:"
ip -6 addr show | grep inet6 | awk '{print $2}' | cut -d/ -f1
